eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
#      defaultZone: http://localhost:8701/eureka, http://localhost:8702/eureka
      defaultZone: http://localhost:8761/eureka
